AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for docker-app
Globals:
  Function:
    Timeout: 3

Resources:
  BucketReceivePillowv1S3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: bucket-receive-pillowv1
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${BucketReceivePillowv1}/*'
            Principal: '*'
  BucketReceivePillowv1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-receive-pillowv1

  BucketStorePillowv1S3Policy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: bucket-store-pillowv1
      PolicyDocument:
        Statement:
          - Action:
              - 's3:*'
            Effect: 'Allow'
            Resource: !Sub 'arn:aws:s3:::${BucketStorePillowv1}/*'
            Principal: '*'
  BucketStorePillowv1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-store-pillowv1

  LambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      FunctionName: !GetAtt DockerPillowFunction.Arn
      Action: 'lambda:InvokeFunction'
      Principal: 's3.amazonaws.com'
      SourceAccount: !Ref 'AWS::AccountId'
      SourceArn: !GetAtt BucketReceivePillowv1.Arn
  DockerPillowFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 60
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: bucket-receive-pillowv1
        - S3WritePolicy:
            BucketName: bucket-store-pillowv1
      Events:
        FileUpload:
          Type: S3
          Properties: 
            Bucket: !Ref BucketReceivePillowv1
            Events: s3:ObjectCreated:*
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.9-v1

Outputs:
  DockerPillowFunction:
    Description: "Docker Lambda Function ARN"
    Value: !GetAtt DockerPillowFunction.Arn
  DockerPillowFunctionIamRole:
    Description: "Implicit IAM Role created for Docker function"
    Value: !GetAtt DockerPillowFunctionRole.Arn
